name: Release sdwu
on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: "1.20"
        run: go version

      - name: Install Go Dependencies
        run: |
          go mod tidy

      - name: Set up UPX
        uses: crazy-max/ghaction-upx@v3.0.0
        with:
          install-only: true
        run: upx --version

      - name: Set up Pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: latest
        run: pnpm --version

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install Node.Js Dependencies
        run: |
          cd ./app
          pnpm i

      - name: Run Command
        run: |
          pwd
          ls -alh
          upx --version
          which pnpm
          pnpm --version
          which go
          go version
          env

      # - name: build-mac
      #   if: matrix.os == 'macos-latest'
      #   run: |
      #     pwd
      #     ls -alh

      # - name: build-ubuntu
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     cd ./ui
      #     make build-linux

      # - name: build-windows
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     cd ./ui
      #     make build-win

      # - name: release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true
      #     files: |
      #       mysqldoc-out/*.exe
      #       mysqldoc-out/*.zip
      #       mysqldoc-out/*.dmg
      #       mysqldoc-out/*.AppImage
      #       mysqldoc-out/*.snap
      #       mysqldoc-out/*.deb
      #       mysqldoc-out/*.rpm
      #       mysqldoc-out/*.tar.gz
      #       mysqldoc-out/*.yml
      #       mysqldoc-out/*.blockmap
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
